//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WACandidates.Classes.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_candidate_information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_candidate_information()
        {
            this.TB_interview_information = new HashSet<TB_interview_information>();
        }
    
        public int IN_candidate_id { get; set; }
        public string VC_name { get; set; }
        public string VC_email { get; set; }
        public string VC_telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_interview_information> TB_interview_information { get; set; }
    }
}
