//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WACandidates.Classes.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_interview_information
    {
        public int IN_interview_id { get; set; }
        public Nullable<int> IN_candidate_id { get; set; }
        public string VC_interview_type { get; set; }
        public Nullable<System.DateTime> DT_date_interview { get; set; }
        public string VC_interview_form { get; set; }
    
        public virtual TB_candidate_information TB_candidate_information { get; set; }
    }
}
